// chengeit-ng/src/app/components/display/header/header.component.ts
import {Component} from '@angular/core';
import {RouterLink} from "@angular/router";
import {BreadcrumbModule} from "primeng/breadcrumb";

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [
    RouterLink,
    BreadcrumbModule
  ],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {

  public routes = [
    {
      url: '/home',
      label: 'Home'
    },
    {
      url: '/faker-data',
      label: 'Faker Data'
    },
    {
      url: '/faker-galleria',
      label: 'Faker Galleria'
    }
  ]


}

<div class="flex justify-content-between p-2">
  <p-breadcrumb [model]="routes" styleClass="border-none">
    <ng-template pTemplate="item" let-item>
      <a [routerLink]="item.url">{{ item.label }}</a>
    </ng-template>
    <ng-template pTemplate="separator"> |</ng-template>
  </p-breadcrumb>

  <div>
    <a href="http://localhost:3000">React Changeis</a>
  </div>
</div>

// changeit-react/src/components/display/Header.tsx
import {Link} from "react-router-dom";

export const Header = () => {
    return (
        <div id='header' className='d-flex flex-row justify-content-between'>
            <div className='nav-links'>
                <Link to='' className=''>Home</Link>
                |
                <Link to='/faker-data' className=''>Faker Data</Link>
                |
                <Link to='/faker-data-carousel' className=''>Faker Data Carousel</Link>
            </div>

            <div className='header-buttons'>
                <a href='http://localhost:4200'>Angular Changeis</a>
            </div>
        </div>
    );
};
